[package]
name = "advent-25"
version = "0.1.0"
edition = "2021"
default-run = "advent-25"

[dependencies]
minilp = "0.2.2"
pprof = { version = "0.13", features = ["flamegraph"] }
rayon = { version = "1.10", optional = true }

[features]
default = ["parallel"]
parallel = ["rayon"]
